### ISSUE TITLE
Cannot use / in stat names

### ISSUE THREAD

**Issue by ixnoahlive** [sndyx/hsl#2]
/ is commonly used for organisational purposes but throws an error when attempted to be used.

![image](https://github.com/sndyx/hsl/assets/70314622/80e73e28-5c72-4e6f-bad5-769adcec942c)

**Comment by sndyx** [comment]
Resolved: `--slash-idents` [compiler flag](https://github.com/sndyx/hsl/blob/master/docs/reference/manifest.md)
